apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-storage
  labels:
    app: prowlarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
