apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  template:
    spec:
      containers:
        - name: prowlarr
          volumeMounts:
            - name: prowlarr-data
              mountPath: /config
      volumes:
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-storage
