apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4
          args:
            - "--entrypoints.web.Address=:80"
            - "--entrypoints.websecure.Address=:443"
            - "--providers.kubernetesingress"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
