apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: websocket
      port: 3012
      protocol: TCP
  selector:
    app: vaultwarden
