apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-openvpn-storage
  labels:
    app: transmission-openvpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
