apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-storage
  labels:
    app: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
