apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-storage
  labels:
    app: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
