apiVersion: v1
kind: Service
metadata:
  name: transmission-openvpn
  labels:
    app: transmission-openvpn
spec:
  ports:
    - name: web-ui
      port: 9091
      protocol: TCP
  selector:
    app: transmission-openvpn
