apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-storage
  labels:
    app: calibre
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
