apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
spec:
  template:
    spec:
      containers:
        - name: calibre
          volumeMounts:
            - name: calibre-data
              mountPath: /config
      volumes:
        - name: calibre-data
          persistentVolumeClaim:
            claimName: calibre-storage
