apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readarr
spec:
  template:
    spec:
      containers:
        - name: readarr
          volumeMounts:
            - name: calibre-data
              mountPath: /library
      volumes:
        - name: calibre-data
          persistentVolumeClaim:
            claimName: calibre-storage
