apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  labels:
    app: loki
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
