apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  template:
    spec:
      containers:
        - name: loki
          volumeMounts:
            - name: loki-storage
              mountPath: /data
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-storage
