apiVersion: v1
kind: Service
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  ports:
    - name: desktop-gui
      port: 8080
      protocol: TCP
    - name: webserver
      port: 8081
      protocol: TCP
  selector:
    app: calibre
