apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  serviceName: calibre
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - image: lscr.io/linuxserver/calibre:arch
          name: calibre
          env:
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - name: desktop-gui
              containerPort: 8080
              protocol: TCP
            - name: webserver
              containerPort: 8081
              protocol: TCP
