bases:
  - ../../base
  - ../../external
resources:
  - ingress.yaml
components:
  - ../../components/longhorn
  - ../../components/dashboard
  - ../../components/wildcard-certificates
  - ../../components/metrics
