apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: promtail-config
    files:
      - promtail.yaml
