apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-storage
  labels:
    app: kavita-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
