homeassistant:
  name: Home
  auth_providers:
    - type: homeassistant
  unit_system: imperial
  time_zone: "America/Los_Angeles"
  currency: USD
  internal_url: "https://homeassistant.local.aeoly.us"

# Kubernetes reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
