apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
spec:
  template:
    spec:
      containers:
        - name: home-assistant
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
      volumes:
        - name: home-assistant-config
          configMap:
            name: home-assistant-config
