apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
      - name: grafana
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana/
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
