namespace: grafana
bases:
  - ../../base
components:
  - ../../components/metrics
  - ../../components/configs
  - ../../components/longhorn
patches:
  - ingress.yaml
configMapGenerator:
  - name: grafana-config
    behavior: replace
    files:
      - grafana.ini
