apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gull-storage
  labels:
    app: gull
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
