apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-storage
  labels:
    app: readarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
