apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-storage
  labels:
    app: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
