apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - deployment.yaml
configMapGenerator:
  - name: grafana-config
    files:
      - grafana.ini
  - name: grafana-datasources
    files:
      - datasources.yaml
